### ISSUE TITLE
Joplin link does not go to https://joplinapp.org/

### ISSUE THREAD

**Issue by ts200x** [luong-komorebi/Awesome-Linux-Software#586]
Link goes to shady looking site https://joplin.cozic.net/

**Comment by DimitrisPa** [comment]
Fixed #587

**Comment by ts200x** [comment]
Still not fixed on the https://github.com/luong-komorebi/Awesome-Linux-Software page.
